jobs:
  include:
    - name: deploy_draft
      if: branch = production
      language: node_js
      node_js:
        - lts/*
      script:
        - npm run test-and-build
      deploy:
        provider: pages
        fqdn: handlebarsjs.com
        repo: handlebars-lang/handlebarsjs.com-github-pages
        target-branch: gh-pages
        skip-cleanup: true
        local_dir: target
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: production

